# Configuration File of BungeeWorld
# Made by Pulsi_, Version v1.5

# Check for new updates of the plugin.
update-checker: true

# The hub settings.
hub:
  # Choose if a player will be teleported
  # to the hub spawn when joining.
  teleport-when-join: true

  # The sound played when teleporting to the hub.
  # ( SOUND_TYPE VOLUME PITCH )
  teleport-sound: "ENTITY_ENDERMAN_TELEPORT 5 1 MASTER"

# The actions that will be executed when a player join.
join-settings:
  title:
    send: true
    # Format: Title;Subtitle;FadeIn;Stay;FadeOut
    text: '&2&lWelcome!;&7Have fun &a&n%player%&7!'

  # Play a sound when a player joins.
  sound:
    play: true
    sound-type: "ENTITY_PLAYER_LEVELUP 5 1 MASTER"

server-settings:
  # Enable to deny player commands like "/plugin:command"
  deny-dots-commands: true

  # Separate the server chat between non-linked worlds.
  isolate-chat: true

  # If enabled, the console will see all the
  # messages of the players in the different worlds.
  show-chat-to-console: true

  # Separate player active effects between non-linked worlds.
  isolate-effects: true

  # Separate enderchest content between non-linked worlds.
  isolate-enderchests: true

  # This will separate the gamemode between worlds.
  isolate-gamemode: true

  # This will separate the health between worlds.
  isolate-health: true

  # This will separate the hunger between worlds.
  isolate-hunger: true

  # This will separate inventory between worlds.
  isolate-inventories: true

  # Clear the player chat when switching world.
  # This will not happen between linked worlds.
  clear-chat: true

# This is the default world config that is
# generated when a new world is registered.
default-world-config:
  spawn: ""
  teleport-to-last-location: false
  teleport-to-spawn-on-join: false
  security:
    deny-message: "&c&lSorry! &7You can't do that here."
    disable-block-place: false
    disable-block-break: false
    disable-mob-spawning: false
    disable-explosions: false
    disable-player-actions: false
    disable-players-drops: false
    disable-players-pickup: false
    disable-fall-damage: false
    disable-pvp: false
  denied-commands:
    deny-message: "Unknown command. Type \"/help\" for help."
    starts-with: []
    single-command: []
  actions-on-join: []
  actions-on-quit: []
  actions-on-death: []
  actions-on-respawn: []
  death-message: "&a%player% &cdied."
  killer-death-message: "&a%player% &chas been killed by &a%killer%"
  killer-weapon-death-message: "&a%player% &chas been killed by &a%killer% &cwith %item%"
  join-message: "&8[&a+&8] &a%player%"
  quit-message: "&8[&c-&8] &a%player%"
  linked-worlds: []