name: BungeeWorld
version: ${version}
main: me.pulsi_.bungeeworld.BungeeWorld
api-version: 1.13
load: POSTWORLD
softdepend:
  - PlaceholderAPI
authors: [ Pulsi_ ]
commands:
  bungeeworld:
    aliases: bw
  hub:
  spawn: