name: BungeeWorld
version: 1.1
main: me.pulsi_.bungeeworld.BungeeWorld
api-version: 1.13
load: STARTUP
softdepend:
  - PlaceholderAPI
authors: [ Pulsi_ ]
commands:
  bungeeworld:
    aliases: bw
  hub:
  spawn: